#!/usr/bin/python
#
# Copyright (c) 2016, Cray Inc.
#  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Consume the output of pwrtest and produce a more useful postmortem.

import json
import sys

try:
    result = json.load(sys.stdin)
except:
    print "postmortem FAIL: Input is not JSON"
    sys.exit(1)

dline = "==================================================================="
sline = "\n-------------------------------------------------------------------"
print dline
print result['date']
total = result['summary']['total']
fails = result['summary']['fail']
skips = result['summary']['skip']
print "Total tests    = {}".format(total)
print "Total skipped  = {}".format(skips)
print "Total failures = {}".format(fails)
if fails == 0 and skips == 0:
    sys.exit(0)

if skips != 0:
    print sline
for subsys in result['subsystems']:
    for test in subsys['tests']:
        if test['result'] != "SKIP":
            continue
        print "Test: {}:{} SKIPPED - {}".format(
            subsys['name'], test['name'], test['reason'])

for subsys in result['subsystems']:
    for test in subsys['tests']:
        if test['result'] != "FAIL":
            continue
        print sline
        print "Test: {}:{}".format(subsys['name'], test['name'])
        try:
            with open(test['output'], 'r') as fd:
                read_data = fd.read()
        except:
            read_data = "File {} not readable".format(test['output'])
        print read_data

print dline
